title: "Il mio blog"
author: "Il mio nome"
description: "Un blog creato con GitHub Pages e Jekyll"
theme: minima

# Abilita i feed RSS
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Le pagine principali (verifica se sono corrette)
header_pages:
  - index.md
  - about.md

# Indica la cartella dei post
collections:
  posts:
    output: true
