title: "Il mio blog"
author: "Il mio nome"
description: "Un blog creato con GitHub Pages e Jekyll"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Aggiungi il percorso del file CSS personalizzato
include:
  - _includes

# Tema minima
minima:
  include_assets: true
