title: "Il mio blog"
author: "Il mio nome"
description: "Un blog creato con GitHub Pages e Jekyll"
theme: minima

# Abilita i feed RSS
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Indica la cartella dei post
collections:
  posts:
    output: true
